version: "3.8"

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
    ports:
      - "3100:3000"   # Expose API on VM port 3100
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    ports:
      - 5433:5432
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myproxy
    # docker-compose.yml (only change this part)
    volumes:
      - ./sql/init_v2.sql:/docker-entrypoint-initdb.d/1-schema.sql
      # Remove old seed for now â€” we'll import manually later
      # No host port exposure to avoid conflicts

  redis:
    image: redis:7
    # No host port exposure to avoid conflicts